<?php 
require('top_foot.inc.php');
require("functions.inc.php");

$_SESSION['where'] = 'industrial';

top();

?>

<h3>Geoserver</h3>
<p>
<a href="http://localhost:8080/geoserver"> Geoserver </a> allows to visualize multiple layers at once. 
Data from this specific layer can be visualized <a href="http://localhost:8080/geoserver/geospatialdb/wms?service=WMS&version=1.1.0&request=GetMap&layers=geospatialdb:peche_poi&styles=&bbox=-7.9998146759259,2.00787037037E-4,8.6945,1.0002047685185&width=768&height=330&srs=EPSG:4326&format=application/openlayers">here</a>
</p>

<h3>Google Earth</h3>
<p>
A live WMS layer is generated by Geoserver and can be imported in Google Earth. To import in Google Earth: Add -> Network Link -> copy link to WMS into Link. 
<br/>
<i>http://localhost:8080/geoserver/geospatialdb/wms/kml?layers=geospatialdb:peche_poi</i> 
</p>

<h3>QGIS</h3>
<p>
In QGIS: Add Layer -> Add PostGIS Layer -> New Connection -> Pick a Name, Service leave blank, Host is <i>localhost</i>, Port is <i>5432</i>, Database is <i>geospatialdb</i> and Username is <i>postgres</i> (Password blank). This method allows to access all layers in the postgres database.

<br/>
Otherwise, you can add a single WMS layer using the link,<br/>
<i>http://localhost:8080/geoserver/geospatialdb/wms/kml?layers=geospatialdb:peche_poi</i> 
<!--<h3>Documentation</h3>-->
</p>
<br/>

<?php
foot();
?>
