DROP TABLE IF EXISTS trawlers.captures_tortue;
CREATE TABLE trawlers.captures_tortue(
   id uuid DEFAULT uuid_generate_v4 (),
   datetime timestamp DEFAULT now(),
   username varchar(100),
   id_route uuid,
   maree varchar(100),
   date date,
   time time,
   id_species uuid,
   n_ind float,
   t_sex integer,
   length float,
   width float,
   ring boolean,
   position_1 integer,
   code_1 varchar(100),
   position_2 integer,
   code_2 varchar(100),
   t_capture integer,
   t_relache integer,
   resumation boolean,
   resumation_res boolean,
   preleve varchar(100),
   camera text,
   photo text,
   remarque text,
   PRIMARY KEY(id)
);
